#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

dir=$(dirname $BASH_SOURCE)

echo "Init submodules"
yadm submodule update --recursive --init

INSTALL_PACMAN="
  neovim # code editor
  alacritty # terminal
  zsh # shell because fish suck
  picom # windows compositor
  maim # screenshot
  exa # ls replacement
  dunst # notification
  playerctl # play-pause, stop,next and prev button
"

sudo pacman -S $INSTALL_PACMAN

ZSH=~/.local/share/oh-my-zsh sh "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

source $(dir)/ohz-plugin

# bootstrap putty so ~/.putty not created
mkdir ${XDG_CONFIG_HOME}/config/putty -p
