#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

dir=$(dirname $BASH_SOURCE)

echo "Init submodules"
yadm submodule update --recursive --init

PACMAN_INSTALL=(
	neovim wezterm fish
	eza zoxide fisher
	fzf mcfly direnv ripgrep
	logrotate

	emptty dunst sway
	waybar picom wl-clipboard
	grim maim
	playerctl

	networkmanager network-manager-applet
	bluez blueman # bluetooth
	zellij tmux
)

sudo pacman -S "${PACMAN_INSTALL[@]}"
# bootstrap putty so ~/.putty not created
mkdir ${XDG_CONFIG_HOME}/putty -p
