[user]
name = "Muhammad Fathurrohim"
email = "m.faturrohim13@gmail.com"

[signing]
backend = "gpg"
behavior = "keep"

[ui]
pager = "bat"
show-cryptographic-signatures = true

[git]
sign-on-push = true


#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[merge-tools.diffconflicts]
program = "nvim"
# merge-args = [
#   "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
#   "-c", "DiffConflicts", "$output", "$base", "$left", "$right",
# ]
merge-args = [
  "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
  "-c", "DiffConflictsWithHistory", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true
